".oh-my-zsh":
  type: "git-repo"
  url: "https://github.com/ohmyzsh/ohmyzsh"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"

".oh-my-zsh/custom/plugins/zsh-completions":
  type: "git-repo"
  url: "https://github.com/zsh-users/zsh-completions"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"

".oh-my-zsh/custom/plugins/zsh-autosuggestions":
  type: "git-repo"
  url: "https://github.com/zsh-users/zsh-autosuggestions"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"

".oh-my-zsh/custom/plugins/zsh-syntax-highlighting":
  type: "git-repo"
  url: "https://github.com/zsh-users/zsh-syntax-highlighting"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"

".oh-my-zsh/custom/plugins/zsh-autocomplete":
  type: "git-repo"
  url: "https://github.com/marlonrichert/zsh-autocomplete"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"

".nvm":
  type: "git-repo"
  url: "https://github.com/nvm-sh/nvm"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"

".pyenv":
  type: "git-repo"
  url: "https://github.com/pyenv/pyenv"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"

".pyenv/plugins/pyenv-doctor":
  type: "git-repo"
  url: "https://github.com/pyenv/pyenv-doctor"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"